### ISSUE TITLE
Remove reference to BlueXP System Manager

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-alerts#4]
### Page URL

https://docs.netapp.com/us-en/bluexp-alerts/alerts-use-alerts.html

### Page title

View alert details in your ONTAP storage environment

### Summary

Please change the page summary to adjust the summary. "BlueXP System Manager" is not the right terminology.

> With BlueXP alerts, you can view alerts associated with your ONTAP storage environment and drill into the details that are linked to BlueXP System Manager.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Updated the page. Closing this.
