### ISSUE TITLE
Article title and sidebar structure should conform to patterns in other BlueXP service docs

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/bluexp-alerts#5]
### Page URL

https://docs.netapp.com/us-en/bluexp-alerts/whats-new.html

### Page title

Release notes: What's new with BlueXP alerts protection

### Summary

In the sidebar, add a "What's new" node under Release notes.

For example: https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html

Change the article's title from "Release notes: What's new with BlueXP alerts protection" to "What's new with BlueXP alerts protection"

For example: https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Updated the left nav bar and changed topic title.
